// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function Build(arg1:main.ProjectConfig):Promise<void>;

export function GetAllImages():Promise<Array<models.Image>>;

export function GetTagByImageId(arg1:number):Promise<Array<models.Tag>>;

export function Greet(arg1:string):Promise<string>;
