// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllImages() {
  return window['go']['main']['App']['GetAllImages']();
}

export function GetTagByImageId(arg1) {
  return window['go']['main']['App']['GetTagByImageId'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
